/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8kV6J4qpVV6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background">
      <div className="rounded-2xl bg-card shadow-lg w-full max-w-md p-6 space-y-6">
        <div className="flex flex-col items-center gap-4">
          <Avatar className="w-20 h-20 border-2 border-card-foreground">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="space-y-1 text-center">
            <div className="text-2xl font-bold text-foreground">John Doe</div>
            <div className="text-sm text-muted-foreground">john@example.com</div>
          </div>
        </div>
        <div className="grid gap-3">
          <Button variant="outline" className="w-full bg-primary text-primary-foreground hover:bg-primary/90">
            Your Orders
          </Button>
          <Button variant="outline" className="w-full bg-primary text-primary-foreground hover:bg-primary/90">
            Edit Profile
          </Button>
        </div>
      </div>
    </div>
  )
}
